# Generated by Django 4.2.1 on 2023-05-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user'),
    ]

    operations = [
         migrations.RenameModel('User', 'User2')
    ]
